- name: Install required system packages
  apt: pkg="{{ item }}" state=installed update-cache=yes
  with_items:
  - nginx
  - openssl
  tags:
    - install

- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags:
    - install
    
- name: nginx base config
  copy: src=files/nginx.conf dest="{{ clojure_uberjar_webapp_nginx_dir }}/nginx.conf"
  notify:
    - reload nginx
  tags:
    - configure

- name: nginx app config
  template:
    # "no-ssl.conf.j2" if clojure_uberjar_webapp_nginx_use_ssl isn't defined or is false
    src: "templates/app-nginx-{{ 'no-' if not (clojure_uberjar_webapp_nginx_use_ssl|d(False)) else '' }}ssl.conf.j2"
    dest: "{{ clojure_uberjar_webapp_nginx_sites_available }}"
  tags:
    - configure
  notify:
    - "nginx config changed"  

- name: nginx link app config
  file: src="{{ clojure_uberjar_webapp_nginx_sites_available }}" dest="{{ clojure_uberjar_webapp_nginx_sites_enabled }}" state=link
  tags:
    - configure